// Generated by scripts/generate_mcp_catalog_artifacts.py — do not edit.
export const MCP_RESOURCE_URIS: readonly string[] = [
  "codimension://catalog",
  "codimension://workspace/status",
  "codimension://project/tree",
  "codimension://deps/summary",
  "codimension://deps/file/{path}",
  "codimension://symbols/summary",
  "codimension://symbols/file/{path}",
  "codimension://graph/import",
  "codimension://graph/call",
  "codimension://graph/control_flow/{function_key}",
  "codimension://graph/impact/{target_key}",
  "codimension://diagram/import",
  "codimension://diagram/call",
  "codimension://diagram/control_flow/{function_key}",
  "codimension://diagram/impact/{target_key}",
  "codimension://cache/stats",
];
