from typing import Any

class Script:
    def __init__(self, code: str, path: str, project: Any | None = ...) -> None: ...
    def infer(self, line: int, column: int) -> list[Any]: ...
    def get_references(self, line: int, column: int) -> list[Any]: ...
