#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate MCP catalog artifacts from codimension_mcp.catalog (source of truth)."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from codimension_mcp.catalog import catalog_resource_uris
from codimension_mcp.catalog_readme import patch_readme_catalog_tables

ROOT = Path(__file__).resolve().parents[1]
VSCODE_URIS_OUT = ROOT / "codimension-vscode" / "src" / "mcpResourceUris.generated.ts"
MCP_README = ROOT / "codimension_mcp" / "README.md"


def render_vscode_resource_uris(uris: list[str]) -> str:
    """Return TypeScript module exporting readonly MCP resource URI templates."""
    lines = ",\n".join(f'  "{uri}"' for uri in uris)
    return (
        "// Generated by scripts/generate_mcp_catalog_artifacts.py — do not edit.\n"
        "export const MCP_RESOURCE_URIS: readonly string[] = [\n"
        f"{lines},\n"
        "];\n"
    )


def write_vscode_resource_uris(*, check: bool) -> int:
    """Write or verify the VS Code generated URI list."""
    content = render_vscode_resource_uris(catalog_resource_uris())
    if check:
        if not VSCODE_URIS_OUT.exists() or VSCODE_URIS_OUT.read_text(encoding="utf-8") != content:
            print(f"Stale artifact: {VSCODE_URIS_OUT}", file=sys.stderr)
            print("Run: python scripts/generate_mcp_catalog_artifacts.py", file=sys.stderr)
            return 1
        return 0
    VSCODE_URIS_OUT.parent.mkdir(parents=True, exist_ok=True)
    VSCODE_URIS_OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {VSCODE_URIS_OUT}")
    return 0


def write_readme_catalog_tables(*, check: bool) -> int:
    """Write or verify README catalog table sections."""
    current = MCP_README.read_text(encoding="utf-8")
    updated = patch_readme_catalog_tables(current)
    if check:
        if current != updated:
            print(f"Stale README tables: {MCP_README}", file=sys.stderr)
            print("Run: python scripts/generate_mcp_catalog_artifacts.py", file=sys.stderr)
            return 1
        return 0
    MCP_README.write_text(updated, encoding="utf-8")
    print(f"Wrote {MCP_README} catalog tables")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate MCP catalog artifacts.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files are stale (CI drift guard).",
    )
    args = parser.parse_args()
    for writer in (write_vscode_resource_uris, write_readme_catalog_tables):
        code = writer(check=args.check)
        if code != 0:
            return code
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
